### ISSUE TITLE
LFS error

### ISSUE THREAD

**Issue by ademlabs** [TheElixZammuto/sunshine-prebuilt#1]
When cloning & checking out, the following error is encountered:

```
Downloading windows/lib/libavcodec.a (18 MB)
Error downloading object: windows/lib/libavcodec.a (2c52496): Smudge error: Error downloading windows/lib/libavcodec.a (2c524967df69fcb66ee31280c90cdcf53eaccea980cb138286b4d8273496468d): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to D:\msys64\home\Arvind\Projects\sunshine-prebuilt\.git\lfs\logs\20210424T223618.9306512.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
error: git-lfs filter-process died of signal 15
fatal: windows/lib/libavcodec.a: smudge filter lfs failed
```

**Comment by TheElixZammuto** [comment]
Like the error suggests, my account got too many requests for Git LFS files. While I'm trying to make a more permanent fix, I'm uploading the libraries on the Releases Tab on Github itself [here](https://github.com/TheElixZammuto/sunshine-prebuilt/releases/tag/1.0.0). You can drop the content inside the pre-compiled folder on sunshine

**Comment by TheElixZammuto** [comment]
I posted this fix on Sunshine's Repository: https://github.com/loki-47-6F-64/sunshine/pull/78

I'm closing this issue since when this is landed this sould be fixed
